=== nationalarchives/ds-caselaw-utils/src/ds_caselaw_utils/schemas/courts/courts.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Raw Court Repository",
  "description": "A list of courts",
  "type": "array",
  "items": {
    "type": "object",
    "title": "Raw Court Group",
    "properties": {
      "name": {
        "type": "string"
      },
      "display_name": {
        "type": ["string", "null"]
      },
      "is_tribunal": {
        "type": "boolean"
      },
      "courts": {
        "type": "array",
        "items": {
          "$ref": "court.schema.json#"
        }
      }
    },
    "required": ["name", "display_name", "is_tribunal", "courts"],
    "additionalProperties": false
  }
}

=== nationalarchives/ds-caselaw-utils/src/autogen/courts.json
[
  {
    "name": "supreme_court",
    "display_name": null,
    "is_tribunal": false,
    "courts": [
      {
        "code": "UKSC",
        "name": "United Kingdom Supreme Court",
        "long_name": "The Supreme Court",
        "link": "https://www.supremecourt.uk/",
        "ncn_pattern": "\\[(\\d{4})\\] (UKSC) (\\d+)",
        "ncn_examples": [
          "[2013] UKSC 42"
        ],
        "param": "uksc",
        "start_year": 2009,
        "selectable": true,
        "listable": true,
        "ended": false,
        "relationships": [
          {
            "court_code": "EWCA-Civil",
            "relationship_type": "hears_appeals_from"
          },
          {
            "court_code": "EWCA-Criminal",
            "relationship_type": "hears_appeals_from"
          }
        ],
        "identifier_iri": "https://www.supremecourt.uk/"
      }
    ]
  },
  {
    "name": "privy_council",
    "display_name": null,
    "is_tribunal": false,
    "courts": [
      {
        "code": "UKPC",
        "name": "Privy Council",
        "long_name": "The Judicial Committee of the Privy Council",
        "link": "https://www.jcpc.uk/",
        "ncn_pattern": "\\[(\\d{4})\\] (UKPC) (\\d+)",
        "ncn_examples": [
          "[2011] UKPC 25"
        ],
        "param": "ukpc",
        "start_year": 2009,
        "selectable": true,
        "listable": true,
        "ended": false,
        "identifier_iri": "https://www.jcpc.uk/"
      }
    ]
  },
  {
    "name": "court_of_appeal",
    "display_name": "Court of Appeal",
    "is_tribunal": false,
    "courts": [
      {
        "code": "EWCA-Civil",
        "grouped_name": "Civil Division",
        "name": "Court of Appeal (Civil Division)",
        "long_name": "The Court of Appeal of England and Wales (Civil Division)",
        "link": "https://www.gov.uk/courts-tribunals/court-of-appeal-civil-division",
        "ncn_pattern": "\\[(\\d{4})\\] (EWCA) (Civ) (\\d+)",
        "ncn_examples": [
          "[2008] EWCA Civ 649"
        ],
        "param": "ewca/civ",
        "start_year": 2001,
        "selectable": true,
        "listable": true,
        "ended": false,
        "relationships": [
          {
            "court_code": "EWHC",
            "relationship_type": "hears_appeals_from"
          },
          {
            "court_code": "EWHC-Family",
            "relationship_type": "hears_appeals_from"
          }
        ],
        "identifier_iri": "https://www.gov.uk/courts-tribunals/court-of-appeal-civil-division"
      },
      {
        "code": "EWCA-Criminal",
        "grouped_name": "Criminal Division",
        "name": "Court of Appeal (Criminal Division)",
        "long_name": "The Court of Appeal of England and Wales (Criminal Division)",
        "link": "https://www.gov.uk/courts-tribunals/court-of-appeal-criminal-division",
        "ncn_pattern": "\\[(\\d{4})\\] (EWCA) (Crim) (\\d+)",
        "ncn_examples": [
          "[2014] EWCA Crim 420"
        ],
        "param": "ewca/crim",
        "start_year": 2003,
        "selectable": true,
        "listable": true,
        "ended": false,
        "relationships": [
          {
            "court_code": "EWCR",
            "relationship_type": "hears_appeals_from"
          }
        ],
        "identifier_iri": "https://www.gov.uk/courts-tribunals/court-of-appeal-criminal-division"
      }
    ]
  },
  {
    "name": "high_court",
    "display_name": "High Court (England and Wales)",
    "is_tribunal": false,
    "courts": [
      {
        "code": "EWHC",
        "name": "High Court",
        "long_name": "The High Court of Justice",
        "link": "https://www.judiciary.uk/courts-and-tribunals/high-court/",
        "selectable": false,
        "listable": false,
        "ended": false,
        "identifier_iri": "https://www.judiciary.uk/courts-and-tribunals/high-court/"
      },
      {
        "code": "EWHC-QBD-Admin",
        "grouped_name": "Administrative Court",
        "name": "High Court (Administrative Court)",
        "long_name": "The Administrative Court (Queen's Bench Division)",
        "link": "https://www.gov.uk/courts-tribunals/administrative-court",
        "ncn_pattern": "\\[(\\d{4})\\] (EWHC) (\\d+) \\((Admin)\\)",
        "ncn_examples": [
          "[2009] EWHC 995 (Admin)"
        ],
        "param": "ewhc/admin",
        "start_year": 2003,
        "selectable": true,
        "listable": true,
        "ended": false,
        "identifier_iri": "https://www.gov.uk/courts-tribunals/administrative-court"
      },
      {
        "code": "EWHC-KBD-Admin",
        "grouped_name": "Administrative Court",
        "name": "High Court (Administrative Court)",
        "long_name": "The Administrative Court (King's Bench Division)",
        "link": "https://www.gov.uk/courts-tribunals/administrative-court",
        "ncn_pattern": "\\[(\\d{4})\\] (EWHC) (\\d+) \\((Admin)\\)",
        "ncn_examples": [
          "[2025] EWHC 2152 (Admin)"
        ],
        "param": "ewhc/admin",
        "start_year": 2022,
        "selectable": false,
        "listable": false,
        "ended": false,
        "identifier_iri": "https://www.gov.uk/courts-tribunals/administrative-court"
      },
      {
        "code": "EWHC-QBD-Admiralty",
        "grouped_name": "Admiralty Court",
        "name": "High Court (Admiralty Division)",
        "long_name": "The Business and Property Courts (Admiralty Court)",
        "link": "https://www.gov.uk/courts-tribunals/admiralty-court",
        "ncn_pattern": "\\[(\\d{4})\\] (EWHC) (\\d+) \\((Admlty)\\)",
        "ncn_examples": [
          "[2018] EWHC 82 (Admlty)"
        ],
        "param": "ewhc/admlty",
        "start_year": 2003,
        "selectable": true,
        "listable": true,
        "ended": false,
        "identifier_iri": "https://www.gov.uk/courts-tribunals/admiralty-court"
      },
      {
        "code": "EWHC-KBD-Admiralty",
        "grouped_name": "Admiralty Court",
        "name": "High Court (Admiralty Division)",
        "long_name": "The Business and Property Courts (Admiralty Court)",
        "link": "https://www.gov.uk/courts-tribunals/admiralty-court",
        "ncn_pattern": "\\[(\\d{4})\\] (EWHC) (\\d+) \\((Admlty)\\)",
        "ncn_examples": [
          "[2024] EWHC 16 (Admlty)"
        ],
        "param": "ewhc/admlty",
        "start_year": 2022,
        "selectable": false,
        "listable": false,
        "ended": false,
        "identifier_iri": "https://www.gov.uk/courts-tribunals/admiralty-court"
      },
      {
        "code": "EWHC-QBD-BusinessAndProperty",
        "grouped_name": "Business and Property Courts",
        "name": "High Court (Business and Property Courts)",
        "long_name": "The Business and Property Courts (Queen's Bench Division)",
        "link": "https://www.gov.uk/courts-tribunals/the-business-and-property-courts",
        "selectable": false,
        "listable": false,
        "ended": false,
        "identifier_iri": "https://www.gov.uk/courts-tribunals/the-business-and-property-courts"
      },
      {
        "code": "EWHC-KBD-BusinessAndProperty",
        "grouped_name": "Business and Property Courts",
        "name": "High Courts (Business and Property Courts)",
        "long_name": "The Business and Property Courts (King's Bench Division)",
        "link": "https://www.gov.uk/courts-tribunals/the-business-and-property-courts",
        "selectable": false,
        "listable": false,
        "ended": false,
        "identifier_iri": "https://www.gov.uk/courts-tribunals/the-business-and-property-courts"
      },
      {
        "code": "EWHC-Chancery-BusinessAndProperty",
        "grouped_name": "Business and Property Courts",
        "name": "High Court (Business and Property Courts)",
        "long_name": "The Business and Property Courts (Chancery Division)",
        "link": "https://www.gov.uk/courts-tribunals/the-business-and-property-courts",
        "selectable": false,
        "listable": false,
        "ended": false,
        "identifier_iri": "https://www.gov.uk/courts-tribunals/the-business-and-property-courts"
      },
      {
        "code": "EWHC-Chancery-Business",
        "grouped_name": "Business List",
        "name": "High Court (Business List)",
        "long_name": "The Business and Property Courts (Business List)",
        "link": "https://www.gov.uk/courts-tribunals/the-business-list",
        "selectable": false,
        "listable": false,
        "ended": false,
        "identifier_iri": "https://www.gov.uk/courts-tribunals/the-business-list"
      },
      {
        "code": "EWHC-Chancery-Appeals",
        "name": "Chancery Appeals",
        "grouped_name": "High Court (Chancery Appeals)",
        "long_name": "The Business and Property Courts (Chancery Appeals)",
        "link": "https://www.gov.uk/courts-tribunals/chancery-division-of-the-high-court",
        "selectable": false,
        "listable": false,
        "ended": false,
        "identifier_iri": "https://www.gov.uk/courts-tribunals/chancery-division-of-the-high-court"
      },
      {
        "code": "EWHC-Chancery",
        "grouped_name": "Chancery Division",
        "name": "High Court (Chancery Division)",
        "long_name": "The Chancery Division of the High Court",
        "link": "https://www.gov.uk/courts-tribunals/chancery-division-of-the-high-court",
        "ncn_pattern": "\\[(\\d{4})\\] (EWHC) (\\d+) \\((Ch)\\)",
        "ncn_examples": [
          "[2016] EWHC 2142 (Ch)"
        ],
        "param": "ewhc/ch",
        "start_year": 2003,
        "selectable": true,
        "listable": true,
        "ended": false,
        "identifier_iri": "https://www.gov.uk/courts-tribunals/chancery-division-of-the-high-court"
      },
      {
        "code": "EWHC-QBD-Commercial-Circuit",
        "grouped_name": "Circuit Commercial Court",
        "name": "High Court (Circuit Commercial Court)",
        "long_name": "The Business and Property Courts (Circuit Commercial Court)",
